config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  get 'categories/search'
  resources :categories, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_idea.rb
class CategoriesIdea

  include ActiveModel::Model
  attr_accessor :body, :name

  with_options presence: true do
    validates :body, :name
  end

  def save
    category = Category.create(name: name)
    Idea.create(body: body, category_id: category.id)
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ideas
  validates :name, uniqueness: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :search_category, only: [:index, :search]

  def index
    set_category_column
  end

  def new
    @category_idea = CategoriesIdea.new
  end

  def create
    @category_idea = CategoriesIdea.new(idea_params)
    if @category_idea.valid?
      @category_idea.save
      return redirect_to action: :index
    else
      render action: :new
    end
  end

  def search
    @results = @p.result.includes(:ideas)
  end
  
  private

  def idea_params
    params.require(:categories_idea).permit(:body, :name)
  end

  def search_category
    @p = Category.ransack(params[:q])
  end

  def set_category_column
    @category_name = Category.select("name").distinct
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/categories/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class="error-message">
         <%= message %>
       </li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/categories/index.html.erb
<div class="header">

  <div class="inner-header">
    <h1 class="title">アイディア管理API</h1>
    <li class='new-post'>
      <%= link_to "New Post", new_category_path, class:"post-btn"%>
    </li>
  </div>

</div>

<div class="body">
  <%= search_form_for @p, url: categories_search_path do |f| %>
    <%= f.label :name_eq, 'カテゴリー' %>
    <%= f.collection_select :name_eq, @category_name, :name, :name,  include_blank: '指定なし' %>
    <br>
    <%= f.submit '検索' %>
  <% end %> 
</div>

app/views/categories/new.html.erb
<div class='form-wrap'>
  <%= form_with(model: @category_idea, class: 'registration-user', url: categories_path, local: true) do |form| %>
    <%= render 'error_messages', model: form.object %>

    <h1>カテゴリーを入力</h1>
    <div class="category-field">
      <%= form.text_field :name, class:"items-text" %>
    </div>

    <h1>アイディアを入力</h1>
    <div class="idea-field">
      <%= form.text_area :body, class:"items-text" %>
    </div>

    <div class="actions">
      <%= form.submit "登録する" %>
    </div>
  <% end %>
</div>

app/views/categories/search.html.erb
<h1>取得結果</h1>

<% if @results.length !=0 %>
  <% @results.each do |result| %>
    <td>
    <br>
    <li>
      <%= result.id %>
      <%= result.name %>
      <% result.ideas.each do |idea| %>
        <%= idea.body %>
      <% end %>
    </li>
  <% end %>
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medpeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>